### PR TITLE
MSAL 1.0 Support

### PR DESCRIPTION
**Pull request by rpdome**
Modify the code so that it supports MSAL 1.0.

I'll only merge this PR in once the MSAL 1.0 bits is published.

### CODE REVIEW

**Comment by tobihagemann** [comment]
That would be great! MSAL 1.0.0 has been out for quite a while now. :smile:

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
Closing.

**Comment by baywet** [comment]
sorry, disregard the last comment, misfire.

**Comment by tobihagemann** [comment]
Sooo... is this going to be merged?

**Comment by baywet** [comment]
at this point I don't know. We have ongoing work to streamline the auth story across platforms for Java. https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/42

**Comment by baywet** [comment]
to give you more insight, once the PR I pointed to gets merged, we'll get all the providers built by Azure, and it looks like what this current library is doing will be covered by that https://github.com/microsoft/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/InteractiveBrowserCredential.java

**Pull request closed without merging**
